name: breadvision
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - cudnn=8.6
  - cuda-toolkit=11.8
  - pip:
      - tensorflow==2.15
      - opencv-python
      - scikit-learn
      - tqdm
      - pillow
